version: '3'

services:
  odoo:
    container_name: odoo-${PROJECT_NAME}
    image: odoo:${ODOO_VERSION}
    restart: always
    ports:
      - ${PORT}:8069
    depends_on:
      - db
    volumes:
      - ./odoo/config/:/etc/odoo
      - ./odoo/addons/:/mnt/extra-addons
      - ./odoo/logs/:/var/log/odoo


  db:
    container_name: postgres-${PROJECT_NAME}
    image: postgres:${POSTGRES_VERSION}
    restart: always
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_USER=${POSTGRES_USER}
      - PGDATA=/var/lib/postgresql/data/pgdata
    volumes:
      - /data/${PROJECT_NAME}:/var/lib/postgresql/data/pgdata

volumes:
  db: {}
